<div class="row mx-0 mt-2">
  <div class="article-list-item text-ellipsis col-10 px-0">
    <?= $article->title($keyword) ?>
  </div>
  <div class="col-2 px-0 text-right">
    <small class="text-muted"><?= H($article->date()) ?></small>
  </div>
</div>
<div class="media mt-1 mb-1">
  <div style="width: 130px; height: 90px;" class="mr-3">
    <img src="<?= $article->image() ?>" 
    style="max-width: 130px; max-height: 90px;">
  </div>
  <div class="media-body">
    <div class="text-muted">
      <?= $article->content() ?>
    </div>
  </div>
</div>
