<div class="clearfix" style="margin-bottom: 50px">
  <div class="card float-left" style="width: 280px; margin-right: 60px;">
    <h6 class="card-header card-header-border">
      <?= T('校级平台用户登录 / Login') ?>
    </h6>
    <div class="card-body" style="padding: 40px 20px 33px; background-color: rgba(246, 246, 246, .6)">
      <?= V('home/index/login') ?>
    </div>
  </div>
  <div class="card float-left"  style="width: 660px;">
    <h6 class="card-header card-header-border">
      <?= T('通知公告 / Notifications') ?>
      <small class="float-right ml-auto">
        <a href="<?= URL('article/notice') ?>" class="text-muted "><?= T('更多') ?></a>
      </small>
    </h6>
    <div class="card-body" data-async="ajax/index/article/notice"></div>
  </div>
</div>

<div class="clearfix" style="margin-bottom: 50px">
  <div class="card float-left" style="width: 280px; margin-right: 60px;">
    <h6 class="card-header card-header-border">
      <?= T('快捷通道') ?>
    </h6>
    <div class="card-body p-0"
    data-async="ajax/index/link/channel">
    </div>
  </div>
  <div class="card float-left"  style="width: 660px;">
    <h6 class="card-header card-header-border">
      <?= T('工作动态 / Works') ?>
      <small class="float-right text-muted ml-auto">
        <a href="<?= URL('article/works') ?>" class="text-muted "><?= T('更多') ?></a>
      </small>
    </h6>
    <div class="card-body" data-async="ajax/index/article/works">
    </div>
  </div>
</div>

<div class="clearfix" style="margin-bottom: 50px">
  <div class="card">
    <h6 class="card-header card-header-border">
      <?= T('仪器展示 / Instrument Show') ?>
      <small class="float-right ml-auto">
        <a href="<?= URL('equipment') ?>" class="text-muted "><?= T('更多') ?></a>
      </small>
    </h6>
    <div class="card-body" data-async="ajax/index/equipment/swiper">
    </div>
  </div>
</div>

<div class="clearfix" style="margin-bottom: 50px">
  <div class="card">
    <h6 class="card-header card-header-border">
      <?= T('院级平台 / School Platform') ?>
    </h6>
    <div class="card-body" data-async="ajax/index/site">
    </div>
  </div>
</div>

<div class="clearfix" style="margin-bottom: 98px">
  <div class="card">
    <h6 class="card-header card-header-border">
      <?= T('友情链接 / Interlink') ?>
    </h6>
    <div class="card-body link-content">
      <nav class="nav nav-fill">
      <?php if ($links->totalCount()) foreach ($links as $link) : ?>
        <a href="<?= URL($link->url) ?>" class="nav-item">
          <img class="img-fluid" src="<?= URL("link/preview/{$link->id}") ?>" />
        </a>
      <?php endforeach ?>
      </nav>
    </div>
  </div>
</div>
