<div id="swiper-carousel" class="swiper-container swiper-container-horizontal" style="margin-bottom: 50px;">
  <div class="swiper-wrapper">
    <?php foreach ($carousel as $image) : ?>
    <div class="swiper-slide" style="width: 1200px;">
      <div class="mask"></div>
      <img class="d-block w-100" style="height: 400px;" src="<?= URL("carousel/preview/{$image->id}") ?>">
    </div>
    <?php endforeach; ?>
  </div>
  <div class="swiper-button-container">
    <div class="swiper-button-next icon-next" style="right: 0;"></div>
    <div class="swiper-button-prev icon-before" style="left: 0;"></div>
  </div>
</div>

<script>
require(['swiper', 'css!../css/swiper'], function (Swiper) {
  var swiper = new Swiper('#swiper-carousel', {
    speed: 600,
    slidesPerView: 'auto',
    spaceBetween: 0,
    centeredSlides: true,
    loop: true,
    loopAdditionalSlides: 1,
    loopedSlides: <?= $carousel->totalCount() ?>,
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    },
    autoplay: {
      delay: 6000,
      stopOnLastSlide: false,
      disableOnInteraction: true,
    }
  })
})
</script>