<ul class="list-group">
  <?php if ($channels->totalCount()) foreach ($channels as $channel) : ?>
  <li class="list-group-item p-0" style="height: 175px;">
    <img src="<?= url("link/preview/{$channel->id}") ?>" />
    <a class="site-title text-white" href="<?= H($channel->url) ?>" 
      style="font-size: 18px; font-weight: 400;"><?= H($channel->name) ?></a>
    <div class="list-group-item-shade"></div>
  </li>
  <?php endforeach; ?>
</ul>