<ul class="list-group">
  <?php if ($channels->totalCount()) foreach ($channels as $channel) : ?>
  <li class="list-group-item" style="height: 175px; padding-top: 90px;
    background: url(<?= url("link/preview/{$channel->id}") ?>) no-repeat;">
    <div class="d-flex justify-content-between">
      <a href="<?= H($channel->url) ?>" class="text-white" 
        style="font-size: 18px; font-weight: 400;"><?= H($channel->name) ?></a>
    </div>
  </li>
  <?php endforeach; ?>
</ul>