<div id="swiper-equipment" class="swiper-container">
  <div class="swiper-wrapper">
  <?php if ($equipments->totalCount()) foreach ($equipments as $equipment) : ?>
    <div class="swiper-slide">
      <div class="swiper-equipment">
        <img class="mx-auto" src="<?= $equipment->icon ?>"/>
      </div>
      <div class="swiper-description">
        <a href="<?= URL("equipment/content/{$equipment->id}") ?>" class="equipment-link"><?= $equipment->name ?></a>
      </div>
    </div>
  <?php endforeach; ?>
  </div>
</div>
<script>
require(['swiper', 'css!../css/swiper'], function (Swiper) {
  var swiper = new Swiper('#swiper-equipment', {
    loop: true,
    speed: 600,
    slidesPerView: 4,
    spaceBetween: 20,
    autoplay: {
      delay: 3000,
      stopOnLastSlide: false,
      disableOnInteraction: true,
    }
  })
})
</script>