<div id="swiper-equipment" class="swiper-container">
  <div class="swiper-wrapper">
  <?php if ($equipments->totalCount()) foreach ($equipments as $equipment) : ?>
    <div class="swiper-card swiper-slide">
      <img class="swiper-img" src="<?= $equipment->icon ?>"/>
      <div class="swiper-description text-center">
        <a href="<?= URL("equipment/content/{$equipment->id}") ?>" class="equipment-link"><?= $equipment->name ?></a>
      </div>
    </div>
  <?php endforeach; ?>
  </div>
</div>
<script>
require(['swiper', 'css!../css/swiper'], function (Swiper) {
  var swiper = new Swiper('#swiper-equipment', {
    loop: true,
    speed: 600,
    slidesPerView: 4,
    slidesOffsetAfter: 1,
    spaceBetween: 20,
    autoplay: {
      delay: 6000,
      stopOnLastSlide: false,
      disableOnInteraction: true,
    }
  })
})
</script>