<div id="carousel" class="carousel slide mb-4" data-ride="carousel">
  <ol class="carousel-indicators">
    <?php 
    $count = $carousel->totalCount();
    for ($i = 0; $i < $count; $i++) :
    ?>
    <li data-target="#carousel" data-slide-to="<?= $i ?>" class="<?= $i == 0 ? 'active' : '' ?>"></li>
    <?php endfor; ?>
  </ol>
  <div class="carousel-inner">
    <?php 
    $flag = true;
    foreach ($carousel as $image) : ?>
    <div class="carousel-item <?= $flag ? 'active' : '' ?>">
      <img class="d-block w-100" src="<?= URL("carousel/preview/{$image->id}") ?>">
    </div>
    <?php 
    $flag = false;
    endforeach; ?>
  </div>
</div>

<script>
require(['main'], function ($) {
  require(['bootstrap'], function () {
    $('.carousel').carousel({
      interval: 3000
    })
  })
})
</script>