<div id="swiper-carousel" class="swiper-container swiper-container-horizontal mb-4">
  <div class="swiper-wrapper">
    <?php foreach ($carousel as $image) : ?>
    <div class="swiper-slide" style="width: 85%;">
      <img class="d-block w-100" src="<?= URL("carousel/preview/{$image->id}") ?>">
    </div>
    <?php endforeach; ?>
  </div>
  <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets">
    <?php 
    $count = $carousel->totalCount();
    for ($i = 0; $i < $count; $i++) :
    ?>
    <span class="swiper-pagination-bullet"></span>
    <?php endfor; ?>
  </div>
</div>

<script>
require(['swiper', 'css!../css/swiper'], function (Swiper) {
  var swiper = new Swiper('#swiper-carousel', {
    speed: 600,
    slidesPerView: 'auto',
    spaceBetween: 0,
    centeredSlides: true,
    loop: true,
    loopAdditionalSlides: 1,
    loopedSlides: <?= $carousel->totalCount() ?>,
    pagination: {
      el: '.swiper-pagination',
      clickable: true,
    },
    autoplay: {
      delay: 6000,
      stopOnLastSlide: false,
      disableOnInteraction: true,
    }
  })
})
</script>