<div class="clearfix mx-auto" style="padding-top: 50px; width: 1000px;">
  <div class="card">
    <h6 class="card-header card-header-border">
      <?= T('友情链接 / Interlink') ?>
    </h6>
    <div class="card-body link-content">
      <nav class="nav nav-fill">
        <?php if ($links->totalCount()) foreach ($links as $link) : ?>
        <a href="<?= URL($link->url) ?>" class="nav-item">
          <img class="img-fluid" src="<?= URL("link/preview/{$link->id}") ?>" />
        </a>
        <?php endforeach ?>
      </nav>
    </div>
  </div>
</div>
