<form class="form-login" method="POST" action="http://less.nankai.edu.cn/lims/login">
  <div class="input-group input-group-sm mb-3">
    <select class="form-control text-muted" name="token_backend">
      <option value="database"><?= T('本地用户') ?></option>
    </select>
    <span class="input-group-addon backend-addon text-muted">
      &gt;
    </span>
  </div>
  <div class="input-group mb-3">
    <span class="input-group-addon text-muted">
      <img src="assets/image/icon/token.png" />
    </span>
    <input name="token" class="form-control" placeholder="<?= T('用户名') ?>">
  </div>
  <div class="input-group" style="margin-bottom: 30px;">
    <span class="input-group-addon text-muted">
      <img src="assets/image/icon/password.png" />
    </span>
    <input name="password" class="form-control" placeholder="<?= T('密 码') ?>">
  </div>
  <input type="submit" class="btn btn-block" name="submit" value="登录">
  <a href="http://less.nankai.edu.cn/lims/signup" class="text-muted text-center d-block p-2">
    <small><?= T('没有账户，点击注册>') ?></small>
  </a>
</form>