<div class="article-list">
  <?php if ($articles->totalCount()) foreach ($articles as $article) : ?>
  <a href="<?= URL("article/content/{$article->id}") ?>" class="d-block article-link">
    <div class="row pb-2 mx-0 mb-3">
      <div class="article-list-item text-ellipsis col-10 px-0">
        <?= H($article->title) ?>
        <small class="text-muted"><?= H($article->content()) ?></small>
      </div>
      <div class="col-2 px-0 text-right">
        <small class="text-muted"><?= H($article->date()) ?></small>
      </div>
    </div>
  </a>
  <?php endforeach; ?>
</div>