<div class="row">
<?php if ($sites->totalCount()) foreach ($sites as $site) : ?>
  <div class="col-3" style="margin-bottom: 10px;" data-url="<?= URL($site->url) ?>">
    <div class="site-container">
      <img class="img-fluid" src="<?= URL("site/preview/{$site->id}") ?>" />
      <p class="site-description text-center"><?= $site->name ?></p>
    </div>
  </div>
<?php endforeach ?>
</div>

<script>
require(['main'], function ($) {
  $('[data-url]').on('click', function(e) {
    var url = $(this).data('url');
    window.open(url);
  })
})
</script>
