<h4 class="font-weight-normal mb-0"><?= T('添加链接') ?></h4>
<ol class="breadcrumb px-0">
  <li class="breadcrumb-item"><a href="<?= URL($item['url']) ?>"><?= T($item['name']) ?></a></li>
  <li class="breadcrumb-item active"><?= T('添加链接') ?></li>
</ol>
<div class="card text-center">
  <div class="card-header text-left px-3 py-2">
    <h5 class="mx-0 my-1"><?= T('链接信息') ?></h5>
  </div>
  <div class="card-body">
    <form class="text-left" method="POST" enctype="multipart/form-data">
      <div class="form-group">
        <label><?= T('链接标题') ?></label>
        <div class="input-group">
          <input class="form-control form-control-sm <?= $form['_errors']['name'] ? 'is-invalid' : '' ?>" 
          placeholder="<?= T('请输入标题') ?>" type="text" name="name"
          value="<?= $form['name'] ? : ($link->name ? : '') ?>">
          <div class="input-group-addon "><?= T('*') ?></div>
        </div>
        <?php if ($form['_errors']['name']) : ?>
        <div class="invalid-feedback ml-auto d-block">
          <?= T($form['_errors']['name']) ?>
        </div>
        <?php endif; ?>
      </div>

      <div class="form-group">
        <label><?= T('链接地址') ?></label>
        <div class="input-group">
          <input class="form-control form-control-sm <?= $form['_errors']['url'] ? 'is-invalid' : '' ?>" 
          placeholder="<?= T('请输入地址 例: http://www.url.com') ?>" type="url" name="url"
          value="<?= $form['url'] ? : ($link->url ? : '') ?>">
          <div class="input-group-addon"><?= T('*') ?></div>
        </div>
        <?php if ($form['_errors']['url']) : ?>
        <div class="invalid-feedback ml-auto d-block">
          <?= T($form['_errors']['url']) ?>
        </div>
        <?php endif; ?>
      </div>

      <div class="form-group">
        <label><?= T('平台图片') ?></label>
        <input name="file" type="file">
        <?php if ($form['_errors']['file']) : ?>
        <div class="invalid-feedback ml-auto d-block">
          <?= T($form['_errors']['file']) ?>
        </div>
        <?php endif; ?>
      </div>
      
      <br />
      <button type="submit" class="btn btn-sm btn-success"><?= T('提交') ?></button>
    </form>
  </div>
</div>

<script>
require(['main'], function ($) {
  require(['fileinput', 'css!../css/fileinput'], function () {
    require(['fileinput/theme', 'fileinput/zh'], function () {
      $("input[name=file]").fileinput({
        language: 'zh',
        theme: 'icomoon',
        showUpload: false,
        allowedFileTypes: ['image']
        <?php if ($link->id && $link->path) : ?>
        , initialPreview: [
          "<img src='<?= URL("link/preview/{$link->id}") ?>' style='width: 100%;' class='file-preview-image' alt='<?= $link->name ?>' title='<?= $link->name ?>'>" +
          "<input type='hidden' name='exists' value='1'/>"
        ],
        initialPreviewConfig: [
          {
            caption: "<?= $link->name ?>"
          }
        ],
        initialPreviewShowDelete: false
        <?php endif; ?>
      })
    })
  })
})
</script>
