<h4 class="font-weight-normal mb-0"><?= T('添加轮播') ?></h4>
<ol class="breadcrumb px-0">
  <li class="breadcrumb-item"><a href="<?= URL($item['url']) ?>"><?= T($item['name']) ?></a></li>
  <li class="breadcrumb-item active"><?= T('添加轮播') ?></li>
</ol>
<div class="card text-center">
  <div class="card-header text-left px-3 py-2">
    <h5 class="mx-0 my-1"><?= T('文件上传') ?></h5>
  </div>
  <div class="card-body">
    <form class="text-left" method="POST" enctype="multipart/form-data">
      <div class="row">
        <div class="col-md-6">
        
          <div class="form-group">
            <label><?= T('图片标题') ?></label>
            <div class="input-group">
              <input class="form-control <?= $form['_errors']['title'] ? 'is-invalid' : '' ?>" 
              placeholder="<?= T('请输入标题') ?>" type="text" name="title"
              value="<?= $form['title'] ? : ($carousel->title ? : '') ?>">
              <div class="input-group-addon "><?= T('*') ?></div>
            </div>
            <?php if ($form['_errors']['title']) : ?>
            <div class="invalid-feedback ml-auto d-block">
              <?= T($form['_errors']['title']) ?>
            </div>
            <?php endif; ?>
          </div>
        </div>

        <div class="col-md-6">
          <div class="form-group">
            <label><?= T('图片序号') ?></label>
            <div class="input-group">
              <input class="form-control <?= $form['_errors']['index'] ? 'is-invalid' : '' ?>" 
              placeholder="<?= T('请输入序号') ?>" type="number" name="index"
              value="<?= $form['index'] ? : ($carousel->index ? : '') ?>">
            </div>
            <?php if ($form['_errors']['index']) : ?>
            <div class="invalid-feedback ml-auto d-block">
              <?= T($form['_errors']['index']) ?>
            </div>
            <?php endif; ?>
          </div>
        </div>
      </div>

      <div class="form-group">
        <label><?= T('选择文件') ?></label>
        <input name="file" type="file">
        <?php if ($form['_errors']['file']) : ?>
        <div class="invalid-feedback ml-auto d-block">
          <?= T($form['_errors']['file']) ?>
        </div>
        <?php endif; ?>
      </div>
      <br />
      <button type="submit" class="btn btn-sm btn-success"><?= T('提交') ?></button>
    </form>
  </div>
</div>

<script>
require(['main'], function ($) {
  require(['fileinput', 'css!../css/fileinput'], function () {
    require(['fileinput/theme', 'fileinput/zh'], function () {
      $("input[name=file]").fileinput({
        language: 'zh',
        theme: 'icomoon',
        showUpload: false,
        allowedFileTypes: ['image']
        <?php if ($carousel->id) : ?>
        , initialPreview: [
          "<img src='<?= URL("carousel/preview/{$carousel->id}") ?>' style='width: 100%;' class='file-preview-image' alt='<?= $carousel->title ?>' title='<?= $carousel->title ?>'>"
        ],
        initialPreviewConfig: [
          {
            caption: "<?= $carousel->title ?>"
          }
        ],
        initialPreviewShowDelete: false
        <?php endif; ?>
      })
    })
  })
})
</script>