---
items:
  user:
    name: 用户管理
    url: admin/user
    icon: users
  article:
    name: 文章管理
    url: admin/article
    icon: paste
  file:
    name: 文件管理
    url: admin/file
    icon: drawer
  carousel:
    name: 首页轮播
    url: admin/carousel
    icon: images
  link:
    name: 友情链接
    url: admin/link
    icon: link
  channel:
    name: 快速通道
    url: admin/channel
    icon: share
  site:
    name: 信息同步
    url: admin/site
    icon: spinner
...