<div class="p-3">
  <div class="card mb-4">
    <h6 class="card-header font-weight-normal text-center">
      <?= T("{$primary} / ") ?>
      <small class='text-dark font-italic'><?= T($secondary) ?></small>
    </h6>
    <div class="card-body" style="min-height: 600px;">
      <div class="article-list">
        <?php if ($articles->totalCount()) foreach ($articles as $article) : ?>
        <div class="row pb-2 mx-0 mb-3">
          <div class="article-list-item text-ellipsis col-10 px-0">
            <?= H($article->title) ?>
          </div>
          <div class="col-2 px-0 text-right">
            <small class="text-muted"><?= H($article->date()) ?></small>
          </div>
        </div>
        <?php endforeach; ?>
      </div>
    </div>
  </div>
  <?= $pagination ?>
</div>