<div class="p-3">
  <div class="card mb-4">
    <h6 class="card-header font-weight-normal text-center">
      <?= T("{$primary} / ") ?>
      <small class='text-dark font-italic'><?= T($secondary) ?></small>
    </h6>
    <div class="card-body" style="min-height: 600px;">
      <div class="article-list">
        <?php if ($articles->totalCount()) foreach ($articles as $article) : ?>
        <a href="<?= URL("article/content/{$article->id}") ?>" class="d-block article-link">
          <?= V('home/article/common/item', ['article' => $article]) ?>
        </a>
        <?php endforeach; ?>
      </div>
    </div>
  </div>
  <?= $pagination ?>
</div>