<div class="p-3">
  <div class="card mb-4">
    <h6 class="card-header font-weight-normal text-center">
      <?= H($article->title) ?>
    </h6>
    <div class="card-body p-0" style="min-height: 600px;">
      <div class="text-muted text-center p-2">
        <?= $article->date ?>
        <?= '星期' . mb_substr('日一二三四五六', date('w', strtotime($article->date)), 1, 'utf-8') ?>
      </div>
      <hr class="m-0" />
      <div class="article-content p-3">
        <?= $article->content ?>
      </div>
    </div>
  </div>
</div>