<div class="p-3">
  <div class="card mb-4">
    <h6 class="card-header font-weight-normal text-center">
      <?= T("{$primary} / ") ?>
      <small class='text-dark font-italic'><?= T($secondary) ?></small>
    </h6>
    <div class="card-body" style="min-height: 600px;">
      <?php foreach ($articles as $article) : ?>
      <a href="<?= URL("article/content/{$article->id}") ?>" class="d-block article-link">
        <div class="media">
          <div style="width: 130px; height: 90px;" class="mr-3">
          <img src="<?= $article->image() ?>" 
          style="max-width: 130px; max-height: 90px;">
          </div>
          <div class="media-body">
            <div class="row m-0">
              <div class="col-9 p-0 text-dark">
                <?= $article->title ?>
              </div>
              <div class="col-3 p-0 text-right text-muted">
                <small class="pr-1"><?= $article->date() ?></small>
              </div>
            </div>
            <div class="text-muted">
            <?= $article->content() ?>
            </div>
          </div>
        </div>
      </a>
      <hr style="border-style: dashed;" />
      <?php endforeach; ?>
    </div>
  </div>
  <?= $pagination ?>
</div>
