<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><?= T('删除文件') ?></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <?= T('您确定删除文件"' . H($carousel->title) . '"吗') ?>
        <form id="carouselDelete" method="post" action="admin/carousel/delete">
          <input type="hidden" name="id" value="<?= $carousel->id ?>">
        </form>
        <br/>
        <div class="text-right">
          <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal"><?= T('关闭') ?></button>
          <button type="submit" class="btn btn-sm btn-danger" form="carouselDelete"><?= T('删除') ?></button>
        </div>
      </div>
    </div>
  </div>
</div>

<script data-ajax>
require(['main'], function ($) {  
  if ($('.modal').length > 0) {
    $(".modal:not(':eq(0)')").remove()
  }
  $('.modal').modal('show')

  $('.modal').on('hidden.bs.modal', function (e) {
    $('.modal').remove()
  })
})
</script>