<div class="p-3 equipment">
  <div class="card mb-4">
    <h6 class="card-header font-weight-normal text-center">
      <?= H($equipment->name) ?>
    </h6>
    <div class="card-body p-5" style="min-height: 600px;">
      <div class="row">
        <div class="col-5">
          <img class="mx-auto equipment-icon p-1" src="<?= $equipment->icon ?>"/>
        </div>
        <div class="col-7">
          <div class="row mb-2">
            <div class="col-3 text-dark"><?= T('联系人：') ?></div>
            <div class="col-9"><?= H($equipment->contact) ?></div>
          </div>
          <div class="row mb-2">
            <div class="col-3 text-dark"><?= T('邮箱：') ?></div>
            <div class="col-9"><?= H($equipment->email) ?></div>
          </div>
          <div class="row mb-2">
            <div class="col-3 text-dark"><?= T('电话：') ?></div>
            <div class="col-9"><?= H($equipment->phone) ?></div>
          </div>
          <div class="row mb-2">
            <div class="col-3 text-dark"><?= T('生产厂家：') ?></div>
            <div class="col-9"><?= H($equipment->manufacturer) ?></div>
          </div>
          <div class="row mb-2">
            <div class="col-3 text-dark"><?= T('型号：') ?></div>
            <div class="col-9"><?= H($equipment->model) ?></div>
          </div>
          <div class="row">
            <div class="col-3 text-dark"><?= T('购置日期：') ?></div>
            <div class="col-9"><?= H(date('Y-m-d', strtotime($equipment->purchased_date))) ?></div>
          </div>
          <dl>
            <dt class="my-3 text-dark font-weight-bold"><?= T('主要规格及技术指标') ?></dt>
            <dd><?= H($equipment->tech_specs ? : '无') ?></dd>
            <dt class="my-3 text-dark font-weight-bold"><?= T('主要功能及特色') ?></dt>
            <dd><?= H($equipment->features ? : '无') ?></dd>
            <dt class="my-3 text-dark font-weight-bold"><?= T('主要附件与配置') ?></dt>
            <dd><?= H($equipment->configs ? : '无') ?></dd>
          </dl>
        </div>
      </div>
    </div>
  </div>
</div>