<div class="container-fluid footer px-0">
  <div class="footer-content mx-auto clearfix">
    <nav class="float-left" aria-label="breadcrumb" role="navigation">
      <ol class="breadcrumb p-0">
        <li class="breadcrumb-item"><a href="<?= URL('intro') ?>"><?= T('平台简介') ?></a></li>
        <li class="breadcrumb-item"><a href="<?= URL('equipment') ?>"><?= T('仪器列表') ?></a></li>
        <li class="breadcrumb-item"><a href="<?= URL('article/notice') ?>"><?= T('通知公告') ?></a></li>
        <li class="breadcrumb-item"><a href="<?= URL('article/rules') ?>"><?= T('规章制度') ?></a></li>
        <li class="breadcrumb-item"><a href="<?= URL('file') ?>"><?= T('文件下载') ?></a></li>
        <li class="breadcrumb-item"><a href="<?= URL('contact') ?>"><?= T('联系我们') ?></a></li>
      </ol>
    </nav>
    <span class="float-right" style="margin-left: 30px;">
      <img style="margin-right: 12px;" src="assets/image/icon/email.png"/>
      <?= T('nkyqpt@nankai.edu.cn') ?>
    </span>
    <span class="float-right">
      <img style="margin-right: 12px;" src="assets/image/icon/phone.png"/>
      <?= T('022-23508139') ?>
    </span>
  </div>
  <div class="container-fluid support">
    <div class="support-content text-center">
      <nav class="nav nav-fill">
        <span class="nav-item text-left"><?= T('地址: 天津市卫津路94号') ?></span>
        <span class="nav-item"><?= T('邮编: 300071') ?></span>
        <span class="nav-item"><?= T('津教备0061号') ?></span>
        <span class="nav-item"><?= T('津ICP备12003308号-1') ?></span>
        <span class="nav-item text-right"><?= T('技术支持：天津市基理科技股份有限公司') ?></span>
      </nav>
    </small>
  </div>
</div>
