<div class="container-fluid header">
  <div class="header-content mx-auto">
    <img style="margin-top: 22px; margin-left: 100px;" src="assets/image/header/logo.png" alt="<?= T('南开大学') ?>" />
    <div class="float-right text-right" style="margin-top: 10px;">
      <a href="http://less.nankai.edu.cn" class="btn btn-link text-white p-0" style="border: none; font-size: 10px">
        <small><?= T('访问旧版') ?></small>
      </a>
      <form action="<?= URL('search') ?>" class="form-inline form-search">
        <div class="input-group input-group-sm ml-auto">
          <input name="keyword" type="search" class="form-control form-control-sm ml-auto" 
          placeholder="<?= T('请输入仪器名称进行搜索') ?>" autocomplete="off">
          <button class="input-group-addon" type="submit">
            <img src="assets/image/icon/search.png"/>
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

<div class="container-fluid navbar p-0">
  <nav class="nav nav-fill mx-auto">
    <a class="nav-item nav-link <?= strpos($active, 'index') !== false ? 'active1' : '' ?>" 
    href="<?= URL('/') ?>"><?= T('首页') ?></a>
    <a class="nav-item nav-link <?= strpos($active, 'equipment') !== false  ? 'active2' : '' ?>" 
    href="<?= URL('equipment') ?>"><?= T('仪器列表') ?></a>
    <a class="nav-item nav-link <?= strpos($active, 'notice') !== false  ? 'active3' : '' ?>"
    href="<?= URL('article/notice') ?>"><?= T('通知公告') ?></a>
    <a class="nav-item nav-link <?= strpos($active, 'rules') !== false  ? 'active4' : '' ?>"
    href="<?= URL('article/rules') ?>"><?= T('规章制度') ?></a>
    <a class="nav-item nav-link <?= strpos($active, 'file') !== false  ? 'active5' : '' ?>"
    href="<?= URL('file') ?>"><?= T('文件下载') ?></a>
    <a class="nav-item nav-link <?= strpos($active, 'contact') !== false  ? 'active6' : '' ?>"
    href="<?= URL('contact') ?>"><?= T('联系我们') ?></a>
  </nav>
</div>