<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
    <title><?= H($title) ?></title>
    <base href="<?= H(URL('/')) ?>">
    <link href="assets/css/bootstrap.css" rel="stylesheet">
    <link href="assets/css/icomoon.css" rel="stylesheet">
    <link href="assets/css/site.css" rel="stylesheet">
    <link href="assets/css/home.css" rel="stylesheet">
    <script data-main="assets/js/main.js" src="assets/js/require.js"></script>
    <link rel="shortcut icon" href="assets/icon/favicon.png">
  </head>
  <body>
    <?= V('layout/home/header', ['active' => $active]) ?>
    <div class="container-fluid p-0">
      <?= $header ?>
    </div>
    <div class="body mx-auto">
      <?= $body ?>
    </div>
    <?= V('layout/home/footer') ?>
  </body>
</html>
