<div class="p-3">
  <div class="card mb-4">
    <h6 class="card-header font-weight-normal text-center">
      <?= T("联系我们 / ") ?>
      <small class='text-dark font-italic'><?= T('Contact') ?></small>
    </h6>
    <div class="card-body p-5" style="min-height: 600px;">
      <div class="row">
        <div class="col-12 px-4">
          <h6><?= T('南开大学实验室设备处') ?></h6>
          <hr class="nankai-hr"/>
          <p class="text-dark"><?= T('电话: ') . T('022-23508139、022-23508813') ?></p>
          <p class="text-dark"><?= T('邮箱: ') . T('nkyqpt@nankai.edu.cn') ?></p>
          <p class="text-dark"><?= T('地址: ') . T('天津市南开区卫津路94号南开大学综合实验楼D404室') ?></p>
        </div>
        <div class="col-12" style="padding: 60px;">
          <img class="img-fluid" style="box-shadow: 10px 10px;"
          src="assets/image/contact.jpeg" />
        </div>
      </div>
    </div>
  </div>
</div>