<div class="p-3">
  <div class="card mb-4">
    <h6 class="card-header font-weight-normal text-center">
      <?= T("平台简介 / ") ?>
      <small class='text-dark font-italic'><?= T('Platform Introduction') ?></small>
    </h6>
    <div class="card-body p-5" style="min-height: 600px;">
      <div class="row">
        <div class="col-5 px-4 text-dark">
          <?= $intro->content ?>
        </div>
        <div class="col-7">
          <img class="img-fluid" style="box-shadow: 10px 10px;"
          src="<?= URL("intro/preview/{$intro->id}") ?>"></img>
        </div>
      </div>
    </div>
  </div>
</div>