<h4 class="font-weight-normal mb-0"><?= T('添加链接') ?></h4>
<ol class="breadcrumb px-0">
  <li class="breadcrumb-item"><a href="<?= URL($item['url']) ?>"><?= T($item['name']) ?></a></li>
  <li class="breadcrumb-item active"><?= T('添加链接') ?></li>
</ol>
<div class="card text-center">
  <div class="card-header text-left px-3 py-2">
    <h5 class="mx-0 my-1"><?= T('链接信息') ?></h5>
  </div>
  <div class="card-body">
    <form class="text-left" method="POST">
      <div class="form-group">
        <label><?= T('链接标题') ?></label>
        <div class="input-group">
          <input class="form-control form-control-sm <?= $form['_errors']['name'] ? 'is-invalid' : '' ?>" 
          placeholder="<?= T('请输入标题') ?>" type="text" name="name"
          value="<?= $form['name'] ? : ($link->name ? : '') ?>">
          <div class="input-group-addon "><?= T('*') ?></div>
        </div>
        <?php if ($form['_errors']['name']) : ?>
        <div class="invalid-feedback ml-auto d-block">
          <?= T($form['_errors']['name']) ?>
        </div>
        <?php endif; ?>
      </div>

      <div class="form-group">
        <label><?= T('链接地址') ?></label>
        <div class="input-group">
          <input class="form-control form-control-sm <?= $form['_errors']['url'] ? 'is-invalid' : '' ?>" 
          placeholder="<?= T('请输入地址 例: http://www.url.com') ?>" type="url" name="url"
          value="<?= $form['url'] ? : ($link->url ? : '') ?>">
          <div class="input-group-addon"><?= T('*') ?></div>
        </div>
        <?php if ($form['_errors']['url']) : ?>
        <div class="invalid-feedback ml-auto d-block">
          <?= T($form['_errors']['url']) ?>
        </div>
        <?php endif; ?>
      </div>
      
      <br />
      <button type="submit" class="btn btn-sm btn-success"><?= T('提交') ?></button>
    </form>
  </div>
</div>
