<nav class="navbar navbar-light px-2">
  <div class="btn-group ml-auto">
    <button type="button" class="btn dropdown-toggle btn-sm" data-toggle="dropdown" 
    aria-haspopup="true" aria-expanded="false">
      <i class="icon-user"></i>
    </button>
    <div class="dropdown-menu dropdown-menu-right">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <a class="dropdown-item" href="#">Something else here</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="<?= URL('logout') ?>"><?= T('登出') ?></a>
    </div>
  </div>
</nav>