<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
    <title><?= H($title) ?></title>
    <base href="<?= H(URL('/')) ?>">
    <link href="assets/css/bootstrap.css" rel="stylesheet">
    <link href="assets/css/icomoon.css" rel="stylesheet">
    <link href="assets/css/site.css" rel="stylesheet">
    <link href="assets/css/dashboard.css" rel="stylesheet">
    <script data-main="assets/js/main.js" src="assets/js/require.js"></script>
    <link rel="shortcut icon" href="assets/icon/favicon.png">
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2 p-0 sidebar">
          <?= $sidebar ?>
        </div>
        <div class="col-md-10 ml-auto p-0">
          <div class="header">
            <?= $header ?>
          </div>
          <div class="px-3 py-4 body">
            <?php if ($_SESSION['alert']) : ?>
            <div class="alert alert-<?= $_SESSION['alert']['type'] ?> alert-dismissible fade show" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <?php 
              echo $_SESSION['alert']['message'];
              unset($_SESSION['alert']);
              ?>
            </div>
            <?php endif; ?>
            <?= $body ?>
          </div>
        </div>
      </div>
    </div>
    <div>
      <?= $footer ?>
    </div>
  </body>
</html>
